name: README Build
on:
  # Runs on request
  workflow_dispatch:
  # Runs everyday at 05:30 UTC
  schedule:
    - cron: "30 5 * * *"
    
# Sets permissions of the GITHUB_TOKEN to allow repository push
permissions:
  contents: write
  
jobs:
  build:
    name: Update README
    runs-on: ubuntu-latest
    steps:
        
        - name: Checkout
          uses: actions/checkout@v4

        - name: Generate README file
          uses: nclsbayona/nclsbayona-readme-action@master
          with:
            wakatime-api-key: ${{ secrets.WAKATIME_API_KEY }}
            github-username: ${{ github.repository_owner }}
            twitter-username: ${{ github.repository_owner }}
            linkedin-username: ${{ github.repository_owner }}
            nasa-api-key: ${{ secrets.NASA_KEY }}
            webpage-url: 'https://nclsbayona.github.io'
            webpage-qr: 'QR.png'
            contributions-url: 'https://raw.githubusercontent.com/nclsbayona/nclsbayona/output/github-contribution-grid-snake-sissa.svg'
            feed_url: "https://nclsbayona.github.io/index.xml"
        - name: Commit changes
          uses: stefanzweifel/git-auto-commit-action@v7
          with:
            commit_message: "docs: :memo: Update documentation"
