name: README Build
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"
    
# Sets permissions of the GITHUB_TOKEN to allow repository push
  
jobs:
  build:
    name: Update README
    runs-on: ubuntu-latest
    steps:
        - name: Generate README file
          uses: nclsbayona/nclsbayona-readme-action@master
          env:
            WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NASA_KEY: ${{ secrets.NASA_KEY }}
