name: README Build
on:
  push:
    branches: [ main ]

  workflow_dispatch:
  schedule:
    - cron: "* */6 * * *"

jobs:
  build:
    name: Update README without activity
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v2
        
        - name: Make virtual environment
          run: python3 -m venv .venv

        - name: Activate virtual environment
          run: source .venv/bin/activate
        
        - name: Install requirements
          run: pip install -r requirements.txt

        - name: Generate README file
          env:
            WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
            OPEN_WEATHER_MAP_KEY: ${{ secrets.OPEN_WEATHER_MAP_KEY }}
            LOCATION: ${{ secrets.LOCATION }}
          run: python main.py
        
        - name: Update with waka section stats
          uses: anmol098/waka-readme-stats@master
          with:
            WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
            SHOW_LINES_OF_CODE: "True"
            SHOW_TIMEZONE: "False"

        - name: Push new README.md
          uses: mikeal/publish-to-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
