name: README Build
on:
  workflow_dispatch:
  schedule:
    - cron: "50 * * * *"

jobs:
  build:
    name: Update README
    runs-on: ubuntu-latest
    steps:
        - name: Generate README file
          uses: nclsbayona/nclsbayona-readme-action@v2
          env:
            WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
